### PR TITLE
[ACHIEVEMENT] Dont yell at me

### PR DESCRIPTION
**Pull request by ortichon**
# Change Summary

 - New Achievement
 
## More info

You get this achievement when you use ALL CAPS or  3 or more exclamation marks(!!!) as your PR title

### CODE REVIEW

**Comment by Thatkookooguy** [comment]
Looks great. Tested locally? Did you use the test DB? :-)

The only thing missing IMO is removing all text inside square brackets. So tags won't be included in the test

**Comment by Thatkookooguy** [comment]
Like this title  "[ACHIEVEMENT] :-)"

**Comment by ortichon** [comment]
Tested locally not using the testDB.
suggested tests (I guess you'll test it yourself too):
title:
1) FOO - 👍 
2) foobar!!! - 👍 
3) FOO!!! - 👍 👍
4) FOO bar - 👎 
5) FOO bar!! - 👎

**Comment by Thatkookooguy** [comment]
@ortichon tell me when you want me to add the first test (when you're not actively working on this branch) and I'll commit it in

**Comment by Thatkookooguy** [comment]
@ortichon a ***ver very very nitpicky suggestion*** from me, so sorry in advance :-))

with your current pull request description, this line is useless: `- New Achievement`

The `More info` section is there if you want to attach a paragraph to your pull request. having photos, urls, bullets on why you chose that solution, etc.
Since you added only one line there it seems like an overkill.

In your description, I think you can just merge the **More info** section with the `- New Achievement` bullet, in either of these two ways:

```
 - New Achievement: **Dont yell at me**
    > You get this achievement when you use ALL CAPS or 3 or more exclamation marks(!!!) as your PR title
```
OR
```
- New Achievement: **Dont yell at me** - You get this achievement when you use ALL CAPS or 3 or more exclamation marks(!!!) as your PR title
```

**Pull request merged**
