### PR TITLE
[BUG] fix case of no statuses to check gives the bi-winning achievement

### LINKED ISSUE #44: Issue with biWinning.achievement
It gives the achievement even if you only have 1 commit without anything in it. Makes it really easy to achieve,

Should consider making it for at least 2 commits in a PR maybe,

Not sure if this is a bug, but wanted to communicate this issue.

### PR DESCRIPTION
**Pull request by Thatkookooguy**
resolves #44

### CODE REVIEW

**Comment by ortichon** [comment]
@Thatkookooguy 
shouldn't it be [BUG] instead of [ISSUE] in the title?
;-)

**Comment by dunaevsky** [comment]
Great, but is still doesn't solve it if you have only 1 commit. Which makes it an uno-winning, correct me if I'm wrong

**Comment by Thatkookooguy** [comment]
@dunaevsky It's not that easy to win. Ask @ortichon and he'll tell you how not easy it is :-)

You need to integrate some test GitHub integration and set it up for even qualify for this

It's not impossible but it's not easy :-)

**Comment by ortichon** [comment]
nit-pick - shouldn't the title be [BUG] instead of [ISSUE]?

**Comment by dunaevsky** [comment]
there's a bug label.

also LGTM

**Comment by Thatkookooguy** [comment]
@ortichon Yup. You're right.

**Comment by Thatkookooguy** [comment]
@dunaevsky you need to use the `GitHub` review system in order for the status of the PR to be green.

image

click on image and then click on image.

There you can select if you want the creator of the pull request to submit a change, to just comment (as part of a review), or approve the PR

**Pull request merged**
